# Generated by Django 3.2.9 on 2021-12-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('nota', models.CharField(max_length=10)),
            ],
        ),
    ]
